### ISSUE TITLE
Fire file browser from main toolbox

### ISSUE THREAD

**Issue by wobi03** [ckeditor/ckeditor4-docs-samples#3]
Hello
I would like to ask for a sample, where one can fire file browser directly from main toolbar icon. The code of ckeditor is quite sophisticated. Just can't figure it out.

Thank you and best regards
Wojtek

**Comment by sculpt0r** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
